name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: 'latest'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: 'npm publish --provenance --access public'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}